export default [
  {
    artist: 'Abdeelgha4',
    title: 'cava',
    source: './songs/source/Abdeelgha4 - cava.mp3',
    thumbnail: './songs/images/Abdeelgha4 - cava.jpg',
  },
  {
    artist: 'Adrian Bujupi & Capital T',
    title: 'Andiamo',
    source: './songs/source/Adrian Bujupi & Capital T - Andiamo.mp3',
    thumbnail: './songs/images/Adrian Bujupi & Capital T - Andiamo.jpg',
  },
  {
    artist: 'Alan Walker & Ava Max',
    title: 'Alone II',
    source: './songs/source/Alan Walker & Ava Max - Alone II.mp3',
    thumbnail: './songs/images/Alan Walker & Ava Max - Alone II.jpg',
  },
  {
    artist: 'Alan Walker',
    title: 'Alone',
    source: './songs/source/Alan Walker - Alone.mp3',
    thumbnail: './songs/images/Alan Walker - Alone.jpg',
  },
  {
    artist: 'Alan Walker',
    title: 'Faded',
    source: './songs/source/Alan Walker - Faded.mp3',
    thumbnail: './songs/images/Alan Walker - Faded.jpg',
  },
  {
    artist: 'Alan Walker',
    title: 'The Spectre',
    source: './songs/source/Alan Walker - The Spectre.mp3',
    thumbnail: './songs/images/Alan Walker - The Spectre.jpg',
  },
  {
    artist: 'Alan Walker, Aura & Tomine Harket',
    title: 'Darkside',
    source: './songs/source/Alan Walker, Aura & Tomine Harket - Darkside.mp3',
    thumbnail:
      './songs/images/Alan Walker, Aura & Tomine Harket - Darkside.jpg',
  },
  {
    artist: 'Alan Walker, K391 & Emelie Hollow',
    title: 'Lily',
    source: './songs/source/Alan Walker, K391 & Emelie Hollow - Lily.mp3',
    thumbnail: './songs/images/Alan Walker, K391 & Emelie Hollow - Lily.jpg',
  },
  {
    artist: 'Alan Walker, Sabrina Carpenter & Farruko',
    title: 'On My Way',
    source:
      './songs/source/Alan Walker, Sabrina Carpenter & Farruko - On My Way.mp3',
    thumbnail:
      './songs/images/Alan Walker, Sabrina Carpenter & Farruko - On My Way.jpg',
  },
  {
    artist: 'Alan Walkers',
    title: 'Unity',
    source: './songs/source/Alan Walkers - Unity.mp3',
    thumbnail: './songs/images/Alan Walkers - Unity.jpg',
  },
  {
    artist: 'Alesso Anitta',
    title: 'Is That For Me',
    source: './songs/source/Alesso Anitta - Is That For Me.mp3',
    thumbnail: './songs/images/Alesso Anitta - Is That For Me.jpg',
  },
  {
    artist: 'Aleyna Tilki',
    title: 'Sen Olsan Bari',
    source: './songs/source/Aleyna Tilki - Sen Olsan Bari.mp3',
    thumbnail: './songs/images/Aleyna Tilki - Sen Olsan Bari.jpg',
  },
  {
    artist: 'Amel Bent & Imen Es',
    title: "jusqu'au bout",
    source: "./songs/source/Amel Bent & Imen Es - jusqu'au bout.mp3",
    thumbnail: "./songs/images/Amel Bent & Imen Es - jusqu'au bout.jpg",
  },
  {
    artist: 'Anas Kareem',
    title: 'Tala2a Al Roussiyeh',
    source: './songs/source/Anas Kareem - Tala2a Al Roussiyeh.mp3',
    thumbnail: './songs/images/Anas Kareem - Tala2a Al Roussiyeh.jpg',
  },
  {
    artist: 'Anne Marie & James Arthur',
    title: 'Rewrite Tthe Stars',
    source: './songs/source/Anne Marie & James Arthur - Rewrite Tthe Stars.mp3',
    thumbnail:
      './songs/images/Anne Marie & James Arthur - Rewrite Tthe Stars.jpg',
  },
  {
    artist: 'Arash',
    title: 'Broken Angel',
    source: './songs/source/Arash - Broken Angel.mp3',
    thumbnail: './songs/images/Arash - Broken Angel.jpg',
  },
  {
    artist: 'Aseel Hameem',
    title: 'Ser Alhayah',
    source: './songs/source/Aseel Hameem - Ser Alhayah.mp3',
    thumbnail: './songs/images/Aseel Hameem - Ser Alhayah.jpg',
  },
  {
    artist: 'Ava Max',
    title: 'Not Your Baby Girl',
    source: './songs/source/Ava Max - Not Your Baby Girl.mp3',
    thumbnail: './songs/images/Ava Max - Not Your Baby Girl.jpg',
  },
  {
    artist: 'Ava Max',
    title: 'So Am I',
    source: './songs/source/Ava Max - So Am I.mp3',
    thumbnail: './songs/images/Ava Max - So Am I.jpg',
  },
  {
    artist: 'Aya Nakamura',
    title: 'Jolie Nana',
    source: './songs/source/Aya Nakamura - Jolie Nana.mp3',
    thumbnail: './songs/images/Aya Nakamura - Jolie Nana.jpg',
  },
  {
    artist: 'Ayyan',
    title: 'Earthquake',
    source: './songs/source/Ayyan - Earthquake.mp3',
    thumbnail: './songs/images/Ayyan - Earthquake.jpg',
  },
  {
    artist: 'Balquees',
    title: 'Taala Tchouf',
    source: './songs/source/Balquees - Taala Tchouf.mp3',
    thumbnail: './songs/images/Balquees - Taala Tchouf.jpg',
  },
  {
    artist: 'Becky G, Natti Natasha',
    title: 'Sin Pijama',
    source: './songs/source/Becky G, Natti Natasha - Sin Pijama.mp3',
    thumbnail: './songs/images/Becky G, Natti Natasha - Sin Pijama.jpg',
  },
  {
    artist: 'Bouchra Elm',
    title: 'Mash Up',
    source: './songs/source/Bouchra Elm - Mash Up.mp3',
    thumbnail: './songs/images/Bouchra Elm - Mash Up.jpg',
  },
  {
    artist: 'Burna Boy',
    title: 'On The Low',
    source: './songs/source/Burna Boy - On The Low.mp3',
    thumbnail: './songs/images/Burna Boy - On The Low.jpg',
  },
  {
    artist: 'Camila Cabello & Dababi',
    title: 'My Oh My',
    source: './songs/source/Camila Cabello & Dababi - My Oh My.mp3',
    thumbnail: './songs/images/Camila Cabello & Dababi - My Oh My.jpg',
  },
  {
    artist: 'Charlie Puth',
    title: 'Attention',
    source: './songs/source/Charlie Puth - Attention.mp3',
    thumbnail: './songs/images/Charlie Puth - Attention.jpg',
  },
  {
    artist: 'Charlie Puth, Selena Gomez',
    title: "We Don't Talk  Anymore",
    source:
      "./songs/source/Charlie Puth, Selena Gomez - We Don't Talk  Anymore.mp3",
    thumbnail:
      "./songs/images/Charlie Puth, Selena Gomez - We Don't Talk  Anymore.jpg",
  },
  {
    artist: 'Clean Bandit',
    title: 'Rather Be',
    source: './songs/source/Clean Bandit - Rather Be.mp3',
    thumbnail: './songs/images/Clean Bandit - Rather Be.jpg',
  },
  {
    artist: 'CNCO, Little Mix',
    title: 'Reggaeton Lento',
    source: './songs/source/CNCO, Little Mix - Reggaeton Lento.mp3',
    thumbnail: './songs/images/CNCO, Little Mix - Reggaeton Lento.jpg',
  },
  {
    artist: 'CRAVATA Salim',
    title: 'Keddab',
    source: './songs/source/CRAVATA Salim - Keddab.mp3',
    thumbnail: './songs/images/CRAVATA Salim - Keddab.jpg',
  },
  {
    artist: 'Dadju',
    title: 'Jaloux',
    source: './songs/source/Dadju - Jaloux.mp3',
    thumbnail: './songs/images/Dadju - Jaloux.jpg',
  },
  {
    artist: 'David Guetta & Justin Bieber',
    title: '2U',
    source: './songs/source/David Guetta & Justin Bieber - 2U.mp3',
    thumbnail: './songs/images/David Guetta & Justin Bieber - 2U.jpg',
  },
  {
    artist: 'Dhurata Dora & Soolking',
    title: 'Zemer',
    source: './songs/source/Dhurata Dora & Soolking - Zemer.mp3',
    thumbnail: './songs/images/Dhurata Dora & Soolking - Zemer.jpg',
  },
  {
    artist: 'Dhurata Dora',
    title: 'Kesh Kesh',
    source: './songs/source/Dhurata Dora - Kesh Kesh.mp3',
    thumbnail: './songs/images/Dhurata Dora - Kesh Kesh.jpg',
  },
  {
    artist: 'DJ Hamida & Tiiw Tiiw',
    title: 'Caabi Do Brazil',
    source: './songs/source/DJ Hamida & Tiiw Tiiw - Caabi Do Brazil.mp3',
    thumbnail: './songs/images/DJ Hamida & Tiiw Tiiw - Caabi Do Brazil.jpg',
  },
  {
    artist: 'DJ Hamida & Tiiw Tiiw',
    title: 'Chaabi Live',
    source: './songs/source/DJ Hamida & Tiiw Tiiw - Chaabi Live.mp3',
    thumbnail: './songs/images/DJ Hamida & Tiiw Tiiw - Chaabi Live.jpg',
  },
  {
    artist: 'DJ Hamida, Mido Belahbib & GSX',
    title: 'Titiza',
    source: './songs/source/DJ Hamida, Mido Belahbib & GSX - Titiza.mp3',
    thumbnail: './songs/images/DJ Hamida, Mido Belahbib & GSX - Titiza.jpg',
  },
  {
    artist: 'Dounia Batma',
    title: 'Nadmana',
    source: './songs/source/Dounia Batma - Nadmana.mp3',
    thumbnail: './songs/images/Dounia Batma - Nadmana.jpg',
  },
  {
    artist: 'Dounia Batma, Carmen Solimane & Youssef Arafat',
    title: 'Adama Ala Adama',
    source:
      './songs/source/Dounia Batma, Carmen Solimane & Youssef Arafat - Adama Ala Adama.mp3',
    thumbnail:
      './songs/images/Dounia Batma, Carmen Solimane & Youssef Arafat - Adama Ala Adama.jpg',
  },
  {
    artist: 'Ed Sheeran & Justin Bieber',
    title: "I Don't Care",
    source: "./songs/source/Ed Sheeran & Justin Bieber - I Don't Care.mp3",
    thumbnail: "./songs/images/Ed Sheeran & Justin Bieber - I Don't Care.jpg",
  },
  {
    artist: 'Ed Sheeran, Camilia Cabello & Cardi B',
    title: 'South Of The Border',
    source:
      './songs/source/Ed Sheeran, Camilia Cabello & Cardi B - South Of The Border.mp3',
    thumbnail:
      './songs/images/Ed Sheeran, Camilia Cabello & Cardi B - South Of The Border.jpg',
  },
  {
    artist: 'ElGrandeToto',
    title: 'Love Nwantiti',
    source: './songs/source/ElGrandeToto - Love Nwantiti.mp3',
    thumbnail: './songs/images/ElGrandeToto - Love Nwantiti.jpg',
  },
  {
    artist: 'Emrah Karaduman & Aleyna Tilki',
    title: 'Cevapsiz Cinlama',
    source:
      './songs/source/Emrah Karaduman & Aleyna Tilki - Cevapsiz Cinlama.mp3',
    thumbnail:
      './songs/images/Emrah Karaduman & Aleyna Tilki - Cevapsiz Cinlama.jpg',
  },
  {
    artist: 'Emy Hetary',
    title: 'Al Hayat Amal',
    source: './songs/source/Emy Hetary - Al Hayat Amal.mp3',
    thumbnail: './songs/images/Emy Hetary - Al Hayat Amal.jpg',
  },
  {
    artist: 'Eva & Keblack Naza',
    title: 'Kitoko',
    source: './songs/source/Eva & Keblack Naza - Kitoko.mp3',
    thumbnail: './songs/images/Eva & Keblack Naza - Kitoko.jpg',
  },
  {
    artist: 'Faouzia',
    title: 'This Mountain',
    source: './songs/source/Faouzia - This Mountain.mp3',
    thumbnail: './songs/images/Faouzia - This Mountain.jpg',
  },
  {
    artist: 'Faouzia',
    title: 'You Dont Even Know Me',
    source: './songs/source/Faouzia - You Dont Even Know Me.mp3',
    thumbnail: './songs/images/Faouzia - You Dont Even Know Me.jpg',
  },
  {
    artist: 'Fnair & Saad Lamjarred',
    title: 'Asif Habibi',
    source: './songs/source/Fnair & Saad Lamjarred - Asif Habibi.mp3',
    thumbnail: './songs/images/Fnair & Saad Lamjarred - Asif Habibi.jpg',
  },
  {
    artist: 'Ghali & Soolking',
    title: 'Jennifer',
    source: './songs/source/Ghali & Soolking - Jennifer.mp3',
    thumbnail: './songs/images/Ghali & Soolking - Jennifer.jpg',
  },
  {
    artist: 'Hatim Ammor',
    title: 'Alach Ya Lil',
    source: './songs/source/Hatim Ammor - Alach Ya Lil.mp3',
    thumbnail: './songs/images/Hatim Ammor - Alach Ya Lil.jpg',
  },
  {
    artist: 'Hatim Ammor',
    title: 'Ya Saken',
    source: './songs/source/Hatim Ammor - Ya Saken.mp3',
    thumbnail: './songs/images/Hatim Ammor - Ya Saken.jpg',
  },
  {
    artist: 'Hind Ziadi',
    title: 'Amore',
    source: './songs/source/Hind Ziadi - Amore.mp3',
    thumbnail: './songs/images/Hind Ziadi - Amore.jpg',
  },
  {
    artist: 'Hind Ziadi',
    title: 'Majnouna',
    source: './songs/source/Hind Ziadi - Majnouna.mp3',
    thumbnail: './songs/images/Hind Ziadi - Majnouna.jpg',
  },
  {
    artist: 'Jax Jones & raye',
    title: "You Don't Know Me",
    source: "./songs/source/Jax Jones & raye - You Don't Know Me.mp3",
    thumbnail: "./songs/images/Jax Jones & raye - You Don't Know Me.jpg",
  },
  {
    artist: 'Jaylann & Beathoven',
    title: 'Chi Wqat',
    source: './songs/source/Jaylann & Beathoven - Chi Wqat.mp3',
    thumbnail: './songs/images/Jaylann & Beathoven - Chi Wqat.jpg',
  },
  {
    artist: 'Jaylann & Beathoven',
    title: 'Etranger',
    source: './songs/source/Jaylann & Beathoven - Etranger.mp3',
    thumbnail: './songs/images/Jaylann & Beathoven - Etranger.jpg',
  },
  {
    artist: 'Jaylann',
    title: 'Allo Allo',
    source: './songs/source/Jaylann - Allo Allo.mp3',
    thumbnail: './songs/images/Jaylann - Allo Allo.jpg',
  },
  {
    artist: 'Jonas Blue, Liam Payne & Lennon Stella',
    title: 'Polaroid',
    source:
      './songs/source/Jonas Blue, Liam Payne & Lennon Stella - Polaroid.mp3',
    thumbnail:
      './songs/images/Jonas Blue, Liam Payne & Lennon Stella - Polaroid.jpg',
  },
  {
    artist: 'JuL',
    title: 'Ma Che Beaute',
    source: './songs/source/JuL - Ma Che Beaute.mp3',
    thumbnail: './songs/images/JuL - Ma Che Beaute.jpg',
  },
  {
    artist: 'K391, Alan Walker & Julie',
    title: 'Ignite',
    source: './songs/source/K391, Alan Walker & Julie - Ignite.mp3',
    thumbnail: './songs/images/K391, Alan Walker & Julie - Ignite.jpg',
  },
  {
    artist: 'Kevin & Yade Lauren',
    title: 'Als Ik Niet Zie',
    source: './songs/source/Kevin & Yade Lauren - Als Ik Niet Zie.mp3',
    thumbnail: './songs/images/Kevin & Yade Lauren - Als Ik Niet Zie.jpg',
  },
  {
    artist: "L'algerino & Soolking",
    title: 'Adios',
    source: "./songs/source/L'algerino & Soolking - Adios.mp3",
    thumbnail: "./songs/images/L'algerino & Soolking - Adios.jpg",
  },
  {
    artist: 'L7or',
    title: 'Hes Biya',
    source: './songs/source/L7or - Hes Biya.mp3',
    thumbnail: './songs/images/L7or - Hes Biya.jpg',
  },
  {
    artist: 'Lbenj & Hazim Jam',
    title: 'La Jiti',
    source: './songs/source/Lbenj & Hazim Jam - La Jiti.mp3',
    thumbnail: './songs/images/Lbenj & Hazim Jam - La Jiti.jpg',
  },
  {
    artist: 'Lbenj',
    title: 'Ok BB',
    source: './songs/source/Lbenj - Ok BB.mp3',
    thumbnail: './songs/images/Lbenj - Ok BB.jpg',
  },
  {
    artist: 'Lbenj, Mounim Slimani & DJ Med',
    title: 'Amoureux tombe',
    source:
      './songs/source/Lbenj, Mounim Slimani & DJ Med - Amoureux tombe.mp3',
    thumbnail:
      './songs/images/Lbenj, Mounim Slimani & DJ Med - Amoureux tombe.jpg',
  },
  {
    artist: 'Lost Sky',
    title: 'Where We Started',
    source: './songs/source/Lost Sky - Where We Started.mp3',
    thumbnail: './songs/images/Lost Sky - Where We Started.jpg',
  },
  {
    artist: 'Mabel',
    title: 'Dont Call Me Up',
    source: './songs/source/Mabel - Dont Call Me Up.mp3',
    thumbnail: './songs/images/Mabel - Dont Call Me Up.jpg',
  },
  {
    artist: 'Mabel',
    title: 'Mad Love',
    source: './songs/source/Mabel - Mad Love.mp3',
    thumbnail: './songs/images/Mabel - Mad Love.jpg',
  },
  {
    artist: 'Maluma',
    title: 'Felices los 4',
    source: './songs/source/Maluma - Felices los 4.mp3',
    thumbnail: './songs/images/Maluma - Felices los 4.jpg',
  },
  {
    artist: 'Maria Nadim',
    title: 'Disk Hyati',
    source: './songs/source/Maria Nadim - Disk Hyati.mp3',
    thumbnail: './songs/images/Maria Nadim - Disk Hyati.jpg',
  },
  {
    artist: 'Muslim',
    title: 'Lalla',
    source: './songs/source/Muslim - Lalla.mp3',
    thumbnail: './songs/images/Muslim - Lalla.jpg',
  },
  {
    artist: 'Myriam Fares',
    title: 'Kifak Enta',
    source: './songs/source/Myriam Fares - Kifak Enta.mp3',
    thumbnail: './songs/images/Myriam Fares - Kifak Enta.jpg',
  },
  {
    artist: 'Nej',
    title: 'I Miss You',
    source: './songs/source/Nej - I Miss You.mp3',
    thumbnail: './songs/images/Nej - I Miss You.jpg',
  },
  {
    artist: 'Nightcore (Dadju)',
    title: 'Jaloux',
    source: './songs/source/Nightcore (Dadju)- Jaloux.mp3',
    thumbnail: './songs/images/Nightcore (Dadju)- Jaloux.jpg',
  },
  {
    artist: 'Nouamane Belaiachi',
    title: 'Allo',
    source: './songs/source/Nouamane Belaiachi - Allo.mp3',
    thumbnail: './songs/images/Nouamane Belaiachi - Allo.jpg',
  },
  {
    artist: 'Nouamane Belaiachi',
    title: 'Jamali',
    source: './songs/source/Nouamane Belaiachi - Jamali.mp3',
    thumbnail: './songs/images/Nouamane Belaiachi - Jamali.jpg',
  },
  {
    artist: 'Rafet El Roman & Derya',
    title: 'Unuturum Elbet',
    source: './songs/source/Rafet El Roman & Derya - Unuturum Elbet.mp3',
    thumbnail: './songs/images/Rafet El Roman & Derya - Unuturum Elbet.jpg',
  },
  {
    artist: 'RedOne',
    title: "D'ont You Need Somebody",
    source: "./songs/source/RedOne - D'ont You Need Somebody.mp3",
    thumbnail: "./songs/images/RedOne - D'ont You Need Somebody.jpg",
  },
  {
    artist: 'Rema',
    title: 'Dumebi',
    source: './songs/source/Rema - Dumebi.mp3',
    thumbnail: './songs/images/Rema - Dumebi.jpg',
  },
  {
    artist: 'Robin Hostin & TobiMorrow',
    title: 'Light It Up',
    source: './songs/source/Robin Hostin & TobiMorrow - Light It Up.mp3',
    thumbnail: './songs/images/Robin Hostin & TobiMorrow - Light It Up.jpg',
  },
  {
    artist: 'RudeLies & Clarx',
    title: 'Erase',
    source: './songs/source/RudeLies & Clarx - Erase.mp3',
    thumbnail: './songs/images/RudeLies & Clarx - Erase.jpg',
  },
  {
    artist: 'Saad Lamjarred',
    title: 'Adda Elkalam',
    source: './songs/source/Saad Lamjarred - Adda Elkalam.mp3',
    thumbnail: './songs/images/Saad Lamjarred - Adda Elkalam.jpg',
  },
  {
    artist: 'Saad Lamjarred',
    title: 'Casablanca',
    source: './songs/source/Saad Lamjarred - Casablanca.mp3',
    thumbnail: './songs/images/Saad Lamjarred - Casablanca.jpg',
  },
  {
    artist: 'Saad Lamjarred',
    title: 'Daba Tzian',
    source: './songs/source/Saad Lamjarred - Daba Tzian.mp3',
    thumbnail: './songs/images/Saad Lamjarred - Daba Tzian.jpg',
  },
  {
    artist: 'Saad Lamjarred',
    title: 'Ghazali',
    source: './songs/source/Saad Lamjarred - Ghazali.mp3',
    thumbnail: './songs/images/Saad Lamjarred - Ghazali.jpg',
  },
  {
    artist: 'Salma Rachid & Don Bigg',
    title: 'Chlounej',
    source: './songs/source/Salma Rachid & Don Bigg - Chlounej.mp3',
    thumbnail: './songs/images/Salma Rachid & Don Bigg - Chlounej.jpg',
  },
  {
    artist: 'Salma Rachid',
    title: 'Ah Ya Liam',
    source: './songs/source/Salma Rachid - Ah Ya Liam.mp3',
    thumbnail: './songs/images/Salma Rachid - Ah Ya Liam.jpg',
  },
  {
    artist: 'Salma Rachid',
    title: 'Darhali Galbi',
    source: './songs/source/Salma Rachid - Darhali Galbi.mp3',
    thumbnail: './songs/images/Salma Rachid - Darhali Galbi.jpg',
  },
  {
    artist: 'Salma Rachid',
    title: 'Kan Kaygol',
    source: './songs/source/Salma Rachid - Kan Kaygol.mp3',
    thumbnail: './songs/images/Salma Rachid - Kan Kaygol.jpg',
  },
  {
    artist: 'Selena Gomez',
    title: 'Let Me Get Me',
    source: './songs/source/Selena Gomez - Let Me Get Me.mp3',
    thumbnail: './songs/images/Selena Gomez - Let Me Get Me.jpg',
  },
  {
    artist: 'Selena Gomez',
    title: 'Souvenir',
    source: './songs/source/Selena Gomez - Souvenir.mp3',
    thumbnail: './songs/images/Selena Gomez - Souvenir.jpg',
  },
  {
    artist: 'Serena',
    title: 'Safari',
    source: './songs/source/Serena - Safari.mp3',
    thumbnail: './songs/images/Serena - Safari.jpg',
  },
  {
    artist: 'Sia',
    title: 'The Greatest',
    source: './songs/source/Sia - The Greatest.mp3',
    thumbnail: './songs/images/Sia - The Greatest.jpg',
  },
  {
    artist: 'Sia',
    title: 'Unstoppable',
    source: './songs/source/Sia - Unstoppable.mp3',
    thumbnail: './songs/images/Sia - Unstoppable.jpg',
  },
  {
    artist: 'Siboy & Benash, Damso',
    title: 'Mobali',
    source: './songs/source/Siboy & Benash, Damso - Mobali.mp3',
    thumbnail: './songs/images/Siboy & Benash, Damso - Mobali.jpg',
  },
  {
    artist: 'Soolking & Cheb Khaled',
    title: 'mirage',
    source: './songs/source/Soolking & Cheb Khaled - mirage.mp3',
    thumbnail: './songs/images/Soolking & Cheb Khaled - mirage.jpg',
  },
  {
    artist: 'Soolking & Cheb Mami',
    title: 'Ca Fait des Annees',
    source: './songs/source/Soolking & Cheb Mami - Ca Fait des Annees.mp3',
    thumbnail: './songs/images/Soolking & Cheb Mami - Ca Fait des Annees.jpg',
  },
  {
    artist: 'Soolking & Dadju',
    title: 'Melegim',
    source: './songs/source/Soolking & Dadju - Melegim.mp3',
    thumbnail: './songs/images/Soolking & Dadju - Melegim.jpg',
  },
  {
    artist: 'Soolking',
    title: 'Leila',
    source: './songs/source/Soolking - Leila.mp3',
    thumbnail: './songs/images/Soolking - Leila.jpg',
  },
  {
    artist: 'Soolking',
    title: 'Milano',
    source: './songs/source/Soolking - Milano.mp3',
    thumbnail: './songs/images/Soolking - Milano.jpg',
  },
  {
    artist: 'Soolking',
    title: 'Rockstar 2',
    source: './songs/source/Soolking - Rockstar 2.mp3',
    thumbnail: './songs/images/Soolking - Rockstar 2.jpg',
  },
  {
    artist: 'Soolking',
    title: 'Rockstar',
    source: './songs/source/Soolking - Rockstar.mp3',
    thumbnail: './songs/images/Soolking - Rockstar.jpg',
  },
  {
    artist: 'Soolking',
    title: 'Tata',
    source: './songs/source/Soolking - Tata.mp3',
    thumbnail: './songs/images/Soolking - Tata.jpg',
  },
  {
    artist: 'Soolking',
    title: 'Vroom Vroom',
    source: './songs/source/Soolking - Vroom Vroom.mp3',
    thumbnail: './songs/images/Soolking - Vroom Vroom.jpg',
  },
  {
    artist: 'Soolking',
    title: 'Youv',
    source: './songs/source/Soolking - Youv.mp3',
    thumbnail: './songs/images/Soolking - Youv.jpg',
  },
  {
    artist: 'Souf & DJ Kayz',
    title: 'Fuego',
    source: './songs/source/Souf & DJ Kayz - Fuego.mp3',
    thumbnail: './songs/images/Souf & DJ Kayz - Fuego.jpg',
  },
  {
    artist: 'Souf',
    title: "ca c'est fait",
    source: "./songs/source/Souf - ca c'est fait.mp3",
    thumbnail: "./songs/images/Souf - ca c'est fait.jpg",
  },
  {
    artist: 'Souf',
    title: 'Mi Amor',
    source: './songs/source/Souf - Mi Amor.mp3',
    thumbnail: './songs/images/Souf - Mi Amor.jpg',
  },
  {
    artist: 'Stephane Legar',
    title: 'Vida Loca',
    source: './songs/source/Stephane Legar - Vida Loca.mp3',
    thumbnail: './songs/images/Stephane Legar - Vida Loca.jpg',
  },
  {
    artist: 'TheFatRat',
    title: 'Rise Up',
    source: './songs/source/TheFatRat - Rise Up.mp3',
    thumbnail: './songs/images/TheFatRat - Rise Up.jpg',
  },
  {
    artist: 'Vitaa',
    title: "T'es ou",
    source: "./songs/source/Vitaa - T'es ou.mp3",
    thumbnail: "./songs/images/Vitaa - T'es ou.jpg",
  },
  {
    artist: 'Youness',
    title: 'Allo Papa',
    source: './songs/source/Youness - Allo Papa.mp3',
    thumbnail: './songs/images/Youness - Allo Papa.jpg',
  },
  {
    artist: 'Youssef Aoutoul',
    title: 'Taralali',
    source: './songs/source/Youssef Aoutoul - Taralali.mp3',
    thumbnail: './songs/images/Youssef Aoutoul - Taralali.jpg',
  },
];
